use_frameworks!

platform :ios, '9.0'

target 'LSJHPickerView_Example' do
  pod 'LSJHPickerView', :path => '../'

  target 'LSJHPickerView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
